sudo: false
branches:
  only:
    - release

language: node_js
node_js:
  - 'lts/carbon'
script: true
after_success:
  - git config user.name 'TravisCI Auto-publisher'
  - git config user.email 'travis-auto-publish@example.com'
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then
      printf '#!/bin/sh -e\necho %s' "$GH_PUBLISH_TOKEN" > gh-publish-pass.sh &&
      chmod u+x gh-publish-pass.sh &&
      cd assets/ && yarn && yarn run build && cd ../ &&
      git add -f assets/bundle.js assets/bundle.css &&
      git commit -m 'Auto-publishing via TravisCI' &&
      GIT_ASKPASS=./gh-publish-pass.sh git push origin +HEAD:refs/heads/master;
    fi
