sudo: false
branches:
  only:
    - release

language: node_js
node_js:
  - 'lts/carbon'
script: true
before_install:
  - gem --version
  - gem install bundler
  - bundle --version
  - bundle install
  - yarn
install:
  - yarn run build
  - bundle exec jekyll build
after_success:
  - git config user.name 'TravisCI Auto-publisher'
  - git config user.email 'travis-auto-publish@example.com'
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then
      GLOBIGNORE='.git:_site' &&
      rm -r * &&
      mv _site/* ./ &&
      rm -r _site/ &&
      git add . &&
      printf '#!/bin/sh -e\necho %s' "$GH_PUBLISH_TOKEN" > gh-publish-pass.sh &&
      chmod u+x gh-publish-pass.sh &&
      git commit -m 'Auto-publishing via TravisCI' &&
      GIT_ASKPASS=./gh-publish-pass.sh git push origin +HEAD:refs/heads/master;
    fi
