title: Mateus Etto
email: mateus.etto@gmail.com
description: >-
  Personal website.
baseurl: ""
url: ""
permalink: /blog/:categories/:year/:month/:day/:title
github_username: Yutsuten
collections:
  - notes
markdown: kramdown
plugins:
  - jekyll-feed
