title: Mateus Etto
email: mateus.etto@gmail.com
description: >-
  Personal website.
baseurl: "/notes"
url: ""
github_username: Yutsuten
collections:
  - notes
markdown: kramdown
plugins:
  - jekyll-feed
