version: '3'
services:
  web:
    build: .
    ports:
      - "4050:4000"
    volumes:
      - .:/code
  assets:
    build:
      context: .
      dockerfile: assets.Dockerfile
    volumes:
      - .:/code
